app.security.secure-cookies=true
app.security.cors-allowed-origins[0]=${FRONTEND_ORIGIN:https://naijacollab.com}
app.security.cors-allowed-origins[1]=${FRONTEND_ORIGIN_WWW:https://www.naijacollab.com}
